### PR TITLE
36 onboard buffer overrun

### PR DESCRIPTION
**Pull request by mximp**
#36 added array buffer overrun case from https://github.com/polystat/clang-tidy-mistakes/blob/master/false-negative/buffer-overrun.cpp

### CODE REVIEW

**Comment by mximp** [comment]
@AlexPotyomkin @yegor256 please check & merge

**Comment by mximp** [comment]
@yegor256 reminder

**Comment by yegor256** [comment]
@rultor merge

**Comment by mximp** [comment]
@yegor256 it seems rultor were unable to clone polystat repo. Is there anything needs to be done on rultor's side to set it up correctly?

**Comment by mximp** [comment]
@yegor256 can you assist?

**Comment by yegor256** [comment]
@rultor merge

**Pull request closed without merging**
