### PR TITLE
Mutual recursion in an inheritance chain

### PR DESCRIPTION
**Pull request by APotyomkin**
Added 4 test cases in which mutual recursion occurs in an inheritance chain

### CODE REVIEW

**Comment by yegor256** [comment]
@APotyomkin I updated the `README` file and made the format of the YAML strict. Please, modify your PR to make sure it strictly abides the format.

**Comment by yegor256** [comment]
@APotyomkin if/when you want me to look at your PR again, post a message here mentioning my name.

**Comment by APotyomkin** [comment]
@yegor256 ok. Please look at the PR

**Comment by yegor256** [comment]
@APotyomkin thanks!

**Pull request merged**
