### PR TITLE
Added a base example of mutual recursion

### PR DESCRIPTION
**Pull request by APotyomkin**
Added a base example of mutual recursion in the YAML file. It reflects the proposed structure of test files.
The code and eoCode section can contain both a breakdown into files and into good bad cases.

### CODE REVIEW

**Comment by yegor256** [comment]
@APotyomkin good first step. Let's rename it to `tests/inheritance/mutual-recursion.yml`. Also, why Java code block doesn't have sub-blocks for different files?

**Comment by APotyomkin** [comment]
@yegor256 I suggest sub-blocks for different files are optional as well as good/bad blocks. Divide if necessary.
The EO code is split into files due to the peculiarities of the Polystat implementation. Is it necessary to achieve full compliance with the code on EO (especially since this is not always possible)?

**Comment by yegor256** [comment]
@APotyomkin what is "full compliance"?

**Comment by APotyomkin** [comment]
@yegor256 in this case, I mean, if EO code is split into files, then the C++ code should be also split into files.

**Comment by yegor256** [comment]
@APotyomkin I updated the `README` file and made the format of the YAML strict. Please, modify your PR to make sure it strictly abides the format.

**Comment by APotyomkin** [comment]
@yegor256 ok, but first I would like to clarify a couple of points about the new format.
1. The `problem` section has been removed, which means that we cannot say what type of errors this test case belongs to.
Such information can be useful, for example, for grouping results by type of error.
2. It is not clear how to handle a few good cases.

**Comment by yegor256** [comment]
@APotyomkin the "problem" is in the name of the file, we already have the grouping mechanism enabled. As for the "good" cases, let's stay away from them for now. Just focus on traditional bugs: one "bad" file and a number of "good" ones (if you need more than one).

**Comment by yegor256** [comment]
@APotyomkin thanks!

**Pull request merged**
